name: "[CD] DEV 클라이언트"
on:
  push:
    branches:
      - dev
    paths:
      - "client/**"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node JS
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Make .env file
        run: |
          echo "VITE_SERVER_URL=${{ secrets.DEV_VITE_SERVER_URL }}" >> .env
          echo "VITE_LOCAL_URL=${{ secrets.DEV_VITE_LOCAL_URL }}" >> .env
          echo "VITE_GITHUB_AUTH_SERVER_URL=${{ secrets.DEV_VITE_GITHUB_AUTH_SERVER_URL }}" >> .env
          echo "VITE_API_MODE=${{ secrets.DEV_VITE_API_MODE }}" >> .env

      - name: Install Npm Clean
        run: npm ci

      - name: Build Npm
        run: npm run build

      - name: Push to NCP Object Storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_NCLOUD_BUCKET_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_NCLOUD_BUCKET_SECRET_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
        run: aws --endpoint-url=https://kr.object.ncloudstorage.com s3 cp --recursive ./dist s3://weview-dev

  pull:
    runs-on: ubuntu-20.04
    needs: build-and-push
    steps:
      - name: Deploy with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_NCLOUD_HOST }}
          username: ${{ secrets.DEV_NCLOUD_USERNAME }}
          password: ${{ secrets.DEV_NCLOUD_PASSWORD }}
          port: ${{ secrets.DEV_NCLOUD_PORT }}
          script: aws --endpoint-url=https://kr.object.ncloudstorage.com s3 cp --recursive s3://weview-dev ./client
