name: "[CI] API 서버(Pull Request)"
on:
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "server/**"
  workflow_dispatch:

jobs:
  reusable:
    uses: ./.github/workflows/reusable-integration.yml
    with:
      working-directory: server
