name: "[CI] 클라이언트(Pull Request)"
on:
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "client/**"
  workflow_dispatch:

jobs:
  reusable:
    uses: ./.github/workflows/reusable-integration.yml
    with:
      working-directory: client
