name: "Main Server Auto Deploy"
on:
  push:
    tags:
      - "v*"
    paths:
      - "server/**"
  workflow_dispatch:
jobs:
  deployment:
    name: deployment
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/weview-main:${{github.ref_name}}

      - name: Deploy with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MAIN_NCLOUD_HOST }}
          username: ${{ secrets.MAIN_NCLOUD_USERNAME }}
          password: ${{ secrets.MAIN_NCLOUD_PASSWORD }}
          port: ${{ secrets.MAIN_NCLOUD_PORT }}
          script: |
            cd /home/weview/server && docker compose pull
            cd /home/weview/server && docker compose up --detach
